context:
  version: "3.10.1"

package:
  name: docusaurus
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@docusaurus/core/-/core-${{ version }}.tgz
  sha256: 73aed21fb3a6954cce5bb56541b057c110b18e3796083c92637fd3cfdcf5897e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - docusaurus 2>&1 | grep -q "No config file found in site dir"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Easy to maintain open source documentation websites.
  homepage: https://github.com/facebook/docusaurus
  repository: https://github.com/facebook/docusaurus

extra:
  recipe-maintainers:
    - danielnachun
