context:
  version: "3.10.0"

package:
  name: docusaurus
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@docusaurus/core/-/core-${{ version }}.tgz
  sha256: 5a968a31eb9eee88c7b499345b8ef4126b738a109ab4711e842076422087208a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - docusaurus 2>&1 | grep -q "No config file found in site dir"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Easy to maintain open source documentation websites.
  homepage: https://github.com/facebook/docusaurus
  repository: https://github.com/facebook/docusaurus

extra:
  recipe-maintainers:
    - danielnachun
